"""
Semantic Memory — distilled knowledge from episodic experience.

Where episodic memory is "what happened," semantic memory is "what I learned."
Insights are generated by the Consolidator when patterns emerge across events.
"""

import json
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional


class SemanticMemory:
    """
    Stores durable, queryable insights/rules derived from production history.
    """

    def __init__(self, memory_dir: Optional[str] = None):
        default_dir = Path(__file__).resolve().parents[3] / "data" / "hermes_memory" / "semantic"
        self.memory_dir = Path(memory_dir) if memory_dir else default_dir
        self.memory_dir.mkdir(parents=True, exist_ok=True)
        self.store_path = self.memory_dir / "insights.json"
        self._insights: List[Dict[str, Any]] = []
        self._load()

    def add_insight(
        self,
        rule: str,
        confidence: float,
        source_events: List[str],
        applies_to: Dict[str, str],
        confirmations: int = 1,
    ) -> str:
        """
        Record a new semantic insight.
        Returns the assigned insight_id.
        """
        insight_id = f"ins_{uuid.uuid4().hex[:8]}"
        insight = {
            "insight_id": insight_id,
            "created_at": datetime.now().isoformat(),
            "rule": rule,
            "confidence": confidence,
            "confirmations": confirmations,
            "source_events": source_events,
            "applies_to": applies_to,
        }
        self._insights.append(insight)
        self._save()
        return insight_id

    def query_relevant(
        self,
        error_category: Optional[str] = None,
        shot_type: Optional[str] = None,
        kernel_id: Optional[str] = None,
        min_confidence: float = 0.5,
        min_confirmations: int = 1,
    ) -> List[Dict[str, Any]]:
        """
        Retrieve insights that match the current production context.
        """
        results = []
        for ins in self._insights:
            if ins["confidence"] < min_confidence:
                continue
            if ins["confirmations"] < min_confirmations:
                continue

            applies = ins.get("applies_to", {})
            matches = True
            if error_category and applies.get("error_category"):
                if applies["error_category"].lower() != error_category.lower():
                    matches = False
            if shot_type and applies.get("shot_type"):
                if shot_type.lower() not in applies["shot_type"].lower():
                    matches = False
            if kernel_id and applies.get("kernel_id"):
                if applies["kernel_id"].lower() != kernel_id.lower():
                    matches = False

            if matches:
                results.append(ins)

        # Sort by confidence descending
        results.sort(key=lambda x: x["confidence"], reverse=True)
        return results

    def get_all_insights(self) -> List[Dict[str, Any]]:
        return list(self._insights)

    def get_stats(self) -> Dict[str, Any]:
        return {
            "total_insights": len(self._insights),
            "avg_confidence": (
                sum(i["confidence"] for i in self._insights) / len(self._insights)
                if self._insights
                else 0.0
            ),
            "high_confidence_count": len([i for i in self._insights if i["confidence"] >= 0.8]),
        }

    def _load(self):
        if self.store_path.exists():
            try:
                with open(self.store_path, "r", encoding="utf-8") as f:
                    self._insights = json.load(f)
            except (json.JSONDecodeError, IOError):
                self._insights = []
        else:
            self._insights = []

    def _save(self):
        with open(self.store_path, "w", encoding="utf-8") as f:
            json.dump(self._insights, f, indent=2, ensure_ascii=False)
