import asyncio
import logging
from typing import List, Dict, Any, Optional, Callable

from core.hermes.memory import EpisodicMemory, SemanticMemory, MemoryConsolidator
from core.consistency.character_consistency_engine import CharacterConsistencyEngine

logger = logging.getLogger("HermesAgent")

# Optional event emitter for dashboard integration.
# Set this to a coroutine function(event_type: str, payload: dict) -> None
# to stream Hermes decision events to the dashboard WebSocket.
_event_emitter: Optional[Callable[[str, Dict[str, Any]], Any]] = None


def set_event_emitter(emitter: Optional[Callable[[str, Dict[str, Any]], Any]]):
    """Register an async event emitter for Hermes decision events."""
    global _event_emitter
    _event_emitter = emitter


async def _emit(event_type: str, payload: Dict[str, Any]):
    """Emit a Hermes event if an emitter is registered."""
    if _event_emitter is not None:
        try:
            await _event_emitter(event_type, payload)
        except Exception:
            pass


class HermesAgent:
    """
    The autonomous decision-making layer with Karpathy-style explicit memory.

    Memory architecture:
      • Episodic  — immutable log of every production attempt & outcome.
      • Semantic  — distilled rules/insights generated by the Consolidator.
      • Consolidator — "dream" process that turns episodes into knowledge.

    Before acting, Hermes queries memory: "Have I seen something like this before?"
    After acting, Hermes records the outcome and learns.
    """

    def __init__(
        self,
        visual_agent=None,
        skill_registry=None,
        kimi_bridge=None,
        session_manager=None,
        episodic_memory: Optional[EpisodicMemory] = None,
        semantic_memory: Optional[SemanticMemory] = None,
        character_engine: Optional[CharacterConsistencyEngine] = None,
    ):
        self.visual_agent = visual_agent
        self.skill_registry = skill_registry
        self.kimi_bridge = kimi_bridge
        self.session_manager = session_manager
        self.character_engine = character_engine
        self._autonomy_score = 0.0

        # Memory subsystems (optional but recommended)
        self.episodic = episodic_memory or EpisodicMemory()
        self.semantic = semantic_memory or SemanticMemory()
        self.consolidator = MemoryConsolidator(self.episodic, self.semantic)

    # ------------------------------------------------------------------
    # Core dispatch
    # ------------------------------------------------------------------

    async def dispatch_shots(
        self,
        shot_list: List[Dict[str, Any]],
        director_result: Dict[str, Any],
    ) -> List[Dict[str, Any]]:
        """
        Dispatch shots to generation, augmenting prompts with learned memory
        when similar past events exist.
        """
        logger.info(f"Hermes: Dispatching {len(shot_list)} shots...")
        await _emit("DISPATCH_START", {"shot_count": len(shot_list)})
        results = []

        for shot in shot_list:
            shot_id = shot.get("shot_id", "UNKNOWN")
            concept = shot.get("description", "")
            intent = shot.get("intent", "high_fidelity_image")
            kernel_id = shot.get("kernel_id", "zimage_turbo")

            await _emit("MEMORY_QUERY", {"shot_id": shot_id, "concept": concept})

            # --- MEMORY RETRIEVAL (Karpathy-style: query before act) ---
            similar = self.episodic.query_similar(
                concept=concept,
                error_category=None,
                kernel_id=kernel_id,
                top_k=2,
            )
            memory_augmentation = ""
            recall_count = len(similar)
            if similar:
                best = similar[0]
                if best.get("success") and best.get("fix_applied"):
                    memory_augmentation = f" [Learned: {best['fix_applied']}]"
                    logger.info(f"[HERMES MEMORY] Recalled fix for {shot_id}: {best['fix_applied'][:60]}...")
                    await _emit("MEMORY_RECALL", {
                        "shot_id": shot_id,
                        "fix": best["fix_applied"],
                        "similarity": best.get("similarity", 0.0),
                    })

            # Also pull semantic insights
            insights = self.semantic.query_relevant(
                error_category=None,
                kernel_id=kernel_id,
                min_confidence=0.6,
                min_confirmations=2,
            )
            if insights:
                top_rule = insights[0]["rule"]
                memory_augmentation += f" [Rule: {top_rule[:80]}...]"
                logger.info(f"[HERMES MEMORY] Applied semantic rule for {shot_id}")
                await _emit("PROMPT_AUGMENT", {
                    "shot_id": shot_id,
                    "rule": top_rule,
                    "recall_count": recall_count + len(insights),
                })

            # Inject memory into prompt if visual agent supports it
            enriched_description = concept + memory_augmentation

            logger.info(f"[HERMES] Dispatching shot: {shot_id}")
            await _emit("DISPATCH_SHOT", {"shot_id": shot_id, "prompt": enriched_description})

            if self.visual_agent and hasattr(self.visual_agent, "generate"):
                # Real path
                result = await self.visual_agent.generate(
                    shot_id=shot_id,
                    description=enriched_description,
                    director_schema=director_result,
                )
            else:
                # Mock path for demo / testing
                await asyncio.sleep(0.3)
                result = {
                    "shot_id": shot_id,
                    "description": enriched_description,
                    "asset_path": f"data/outputs/demo/{shot_id}.png",
                    "status": "complete",
                }

            results.append(result)

            # Record the dispatch event
            self.episodic.record({
                "session_id": getattr(self.session_manager, "session_id", "unknown"),
                "shot_id": shot_id,
                "event_type": "generation_attempt",
                "concept": concept,
                "intent": intent,
                "kernel_id": kernel_id,
                "prompt_used": enriched_description,
                "memory_recall_count": len(similar) + len(insights),
            })

        await _emit("DISPATCH_COMPLETE", {"shot_count": len(shot_list)})
        return results

    # ------------------------------------------------------------------
    # Learning hooks — called by RemediationLoop after audit
    # ------------------------------------------------------------------

    def record_outcome(
        self,
        shot_id: str,
        concept: str,
        kernel_id: str,
        success: bool,
        iterations_required: int,
        error_category: Optional[str] = None,
        fix_applied: Optional[str] = None,
        audit_score: float = 0.0,
    ):
        """
        Record the final outcome of a shot. Called by RemediationLoop
        after all iterations are complete.
        """
        self.episodic.record({
            "session_id": getattr(self.session_manager, "session_id", "unknown"),
            "shot_id": shot_id,
            "event_type": "outcome",
            "concept": concept,
            "kernel_id": kernel_id,
            "success": success,
            "iterations_required": iterations_required,
            "error_category": error_category or "general",
            "fix_applied": fix_applied or "none",
            "audit_score": audit_score,
        })
        logger.info(
            f"[HERMES MEMORY] Recorded outcome for {shot_id}: "
            f"success={success}, iterations={iterations_required}"
        )
        # Fire-and-forget event emission (sync-safe)
        try:
            loop = asyncio.get_running_loop()
            loop.create_task(_emit("OUTCOME_RECORD", {
                "shot_id": shot_id,
                "success": success,
                "score": audit_score,
                "error_category": error_category,
                "fix": fix_applied,
            }))
        except RuntimeError:
            pass  # No running loop, skip emission

    async def consolidate_session(self, session_events: List[Dict[str, Any]] = None):
        """
        Trigger the 'dream' process: turn recent episodes into semantic rules.
        Returns list of new insights generated.
        """
        await _emit("CONSOLIDATION_START", {"event_count": len(session_events) if session_events else "all"})
        new_insights = self.consolidator.consolidate(session_events)
        if new_insights:
            logger.info(f"[HERMES MEMORY] Consolidated {len(new_insights)} new insights")
            for ins in new_insights:
                await _emit("INSIGHT_BORN", {
                    "insight_id": ins.get("insight_id", ""),
                    "rule": ins.get("rule", ""),
                    "confidence": ins.get("confidence", 0),
                })
        return new_insights

    # ------------------------------------------------------------------
    # Introspection helpers (hackathon viz)
    # ------------------------------------------------------------------

    def get_memory_summary(self) -> Dict[str, Any]:
        """Returns a JSON-serializable snapshot of Hermes' current knowledge."""
        return {
            "episodic_stats": self.episodic.get_stats(),
            "semantic_stats": self.semantic.get_stats(),
            "autonomy_score": self._autonomy_score,
        }

    def get_recent_experiences(self, n: int = 5) -> List[Dict[str, Any]]:
        return self.episodic.get_recent(n)

    def get_active_rules(self) -> List[Dict[str, Any]]:
        return self.semantic.get_all_insights()

    # ------------------------------------------------------------------
    # Legacy compatibility
    # ------------------------------------------------------------------

    @property
    def autonomy_score(self) -> float:
        return self._autonomy_score

    def set_autonomy_score(self, score: float):
        self._autonomy_score = score
